import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import SubscriptionEmail from './components/subemail'
import Step1 from './components/step1'
import Step2 from './components/step2'


export default function Home() {
  return (
    <>
      <Head>
        <title> Pay Via UPI </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <Script src='static/libs/main.js'
    data-name="pay-via-upi"
    data-cfasync="false"
    data-pa="pratiksharma@boi"
    data-tn=""
    data-cu="INR"
    data-pn="Pratik Sharma"
    data-amount_list = "100, 500, 1000, 2000"
    data-label = "Donate via UPI"
    data-description="Scan and Pay using UPI!"
    data-color="#000"
    data-position="Right"
  
  strategy="beforeInteractive" ></Script>
      <nav>

        <li className='logo'>Pay Via UPI</li>
      </nav>
      <div className={styles.container}>

      <main className={styles.main}>
        <h1>Add  
       
          UPI Payment
    
            Option
            <br/>
             to your Website
            <br/>
            Under 60 Seconds.
        </h1>
        <button className='getStated'>
          Get Started
        </button>
      <SubscriptionEmail/>
      <Step1/>
      <Step2/>

      </main>

      <main className={styles.container}>
        <div></div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://twitter.com/biomathcode"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by { "\u2800"}
          <span className={styles.logo}>
  
          Pratik Sharma
          </span>
        </a>
      </footer>
    </div>
    </>
    
  )
}
